server:
  port: 8082

redis:
  sdk:
    config:
      host: 117.72.36.124
      port: 6379
      username: ${redis_username}
      password: ${redis_password}
      pool-size: 64
      minIdleSize: 10



